fn main() {
    
    // Listing 1-1: A program that prints Hello, world!
    println!("Hello, world!");

    // Listing 1-2: Contents of Cargo.toml generated by cargo new
    
    // In mtuci-rs/homework_1/Cargo.toml
    // [package]
    // name = "homework_1" (in listing name = "hello_cargo")
    // version = "0.1.0"
    // edition = "2021"
    // 
    // # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
    // 
    // [dependencies]

    
}